services:

  mysql8:
    image: mysql:8.0
    container_name: mysql8_bd1
    restart: unless-stopped
    env_file:
      - mysql8.env
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - mydata:/var/lib/mysql/
      - mylogs:/var/log/mysql/
      - init:/docker-entrypoint-initdb.d/
      - scripts:/scripts

volumes:
  mydata:
  mylogs:
  init:
  scripts:


networks:
  my-network:
    driver: bridge


  # client:
  #   image: alpine:latest
  #   container_name: sqlClient
  #   # command: sh -c "apk add mysql-client && mysqldump -u root -p root_password -h mysql8 northwind < schema.sql"
  #   command: ["sleep", "infinity"]
  #   restart: unless-stopped
  #   volumes:
  #     - scripts:/scripts
  #   networks:
  #     - my-network
  #   depends_on:
  #     - mysql8