version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    env_file:
      - mysql8.env
    ports:
      - "3306:3306"
    volumes:
      - ./mydata:/var/lib/mysql
      - ./mylogs:/var/log/mysql

volumes:
  mysql_data:
    driver: local



