version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_server
    env_file:
      - mysql8.env
    ports:
      - "3306:3306"
    volumes:
      - ./mydata:/var/lib/mysql
      - ./mylogs:/var/log/mysql

volumes:
  mysql_data:
    driver: local






# version: '3.3'services:
#   db:
#     image: mysql:5.7
#     restart: always
#     environment:
#       MYSQL_DATABASE: 'db'
#       # So you don't have to use root, but you can if you like
#       MYSQL_USER: 'user'
#       # You can use whatever password you like
#       MYSQL_PASSWORD: 'password'
#       # Password for root access
#       MYSQL_ROOT_PASSWORD: 'password'
#     ports:
#       # <Port exposed> : <MySQL Port running inside container>
#       - '3306:3306'
#     expose:
#       # Opens port 3306 on the container
#       - '3306'
#       # Where our data will be persisted
#     volumes:
#       - my-db:/var/lib/mysql
# # Names our volume
# volumes:
#   my-db:

#   # mongo-express:
#   #   image: mongo-express:latest
#   #   container_name: mongo-express
#   #   restart: always
#   #   environment:
#   #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
#   #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
#   #     ME_CONFIG_MONGODB_PORT: 27017
#   #     ME_CONFIG_MONGODB_SERVER: 'mongodb'
#   #     ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USERNAME}
#   #     ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}
#   #   ports:
#   #     - 8081:8081
#   #   networks:
#   #     - mongodb_network
#   #   depends_on:
#   #     - mongodb

# volumes:
#   mongodb-data:
#     driver: local
#     name: mongo-data
#   mongodb-log:
#     driver: local
#     name: mongo-log

# # networks:
# #   mongodb_network:
# #     driver: bridge
# #     name: mongo-network