services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    restart: always
    env_file:
      - mysql8.env
    ports:
      - "3306:3306"
    volumes:
      - ./mydata:/var/lib/mysql
      - ./mylogs:/var/log/mysql
      - ./init:/docker-entrypoint-initdb.d

volumes:
  mydata:
    driver: local
  mylogs:
    driver: local
  init:
    driver: local



